# Site settings
title: Hadar Shavit
description: PhD Candidate @ RWTH Aachen
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hadar Shavit
user_description: I'm a PhD Candidate at the Chair of AI Methodologies at RWTH Aachen University. My research focus is AutoAI for NP-Complete problems, with focus on nueral network verificatio.
user_title: PhD Candidate
email: shavit@aim.rwth-aachen.de
twitter_username: HadarShavit
#linkedin_username: murraco
github_username:  hadarshavit
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

